services:
  app-service:
    image: yoloslaw/app-service:latest
    restart: "always"
    expose:
      - 8000
    labels:
      traefik.enable: "true"

      traefik.http.middlewares.secure-mw.redirectscheme.permanent: "false"
      traefik.http.middlewares.secure-mv.redirectscheme.scheme: "https"

      traefik.http.middlewares.app-mv.chain.middlewares: "secure-mv"

      traefik.http.middlewares.strip-app-mv.stripprefix.prefixes: "/app"

      traefik.http.routers.app-service.entrypoints: "web"
      traefik.http.routers.app-service.rule: "PathPrefix(`/app`)"
      
      traefik.http.services.app-service.loadbalancer.server.port: "8000"

      traefik.http.routers.app-service-http.middlewares: "app-mv"
      traefik.http.routers.app-service-secure.entrypoints: "websecure"
      traefik.http.routers.app-service-secure.rule: "PathPrefix(`/app`)"

      traefik.http.routers.app-service-secure.tls: "true"
      traefik.http.routers.app-service-secure.middlewares: "strip-app-mv"

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK_NAME}
